spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecommed_db
    username: postgres
    password: root
    hikari:
      pool-name: EcomPool
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
utils:
  jwt:
    expiry: 10
    secret: "8f2c9a1e7d4b6f3a0c9d8e7f1b2a5c6d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4"
  admin:
    name: Dikshanta Acharya
    username: dikshantaacharya04@gmail.com
    password: root
